### ISSUE TITLE
Is there any way to send prompt to midjourney api on discord server and get the resulted image in Flutter? 

### ISSUE THREAD

**Issue by afjal1** [MeixDev/discord_api_flutter#2]
If possible please guide me Or. Give me some hint

Thanks

**Comment by MeixDev** [comment]
I don't see how this would be done with this package alone. Sounds like you want interaction inside a Discord server, in which case you want a bot user. This isn't the purpose of this package, and you should go check `nyxx` instead. 

Furthermore, I won't help out with any Web3 related or AI-generated images related inquiries.

Have a good day :)
